version: '3.3'

services:
  webapi:
    image: isgrupa
    ports:
      - "5000:5000"
      - "5002:22"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: arnau
      MYSQL_PASSWORD: isgrupA
      MYSQL_DB: integracioSistemes
    command: sh -c "service ssh start && service mysql stop && usermod -d /var/lib/mysql/ mysql && service mysql start && cd /home/basedades/is-grupA/db/src && python3 app.py"
    restart: on-failure

  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: integracioSistemes
      MYSQL_USER: arnau
      MYSQL_PASSWORD: isgrupA
    volumes:
      - type: volume
        source: mysql-data
        target: /home/arnau/database

  webboard:
    image: isgrupa
    command: sh -c "service ssh start && cd /home/web/is-grupA/web-board && node -v && npm -v && npm install && npm start"
    ports:
      - "5001:3000"
      - "5003:22"
    depends_on:
      - webapi

volumes:
  mysql-data:
